### ISSUE TITLE
extract getDeviceId & related functionality from fh-js-sdk to fh-sync-js

### ISSUE THREAD

**Issue by damienomurchu** [feedhenry/fh-sync-js#19]
### Issue:
Data records not being processed properly from fhsync_pending_queue in mongo once synced from client to backend

### Cause:
cuid not being picked up by fh-sync-js code, as relevant getDeviceId & related functionality not extracted from fh-js-sdk to fh-sync-js

### Solution:
Extract getDeviceId & related functionality from fh-js-sdk to fh-sync-js/ have another means for client to uniquely identify itself via an id 

### Additional:
E2E test client & server records are synced & persisted into mongodb fully

ping @wtrocki

**Comment by damienomurchu** [comment]
log sample from sync server (w/ dropped request & blank cuid):

`[test1] invalid pendingChange request dropped :: item = {"inFlight":true,"action":"create","post":"valuePosted2","postHash":"db647239d114b2c2d4de7e330837b5c20759dd4d","timestamp":1497429334263,"hash":"a5a615ff198583943e29e7dd089887600b99ee20","uid":"a5a615ff198583943e29e7dd089887600b99ee20","inFlightDate":1497430670723,"crashed":false,"crashedCount":11,"datasetId":"test1","cuid":"","meta_data":{},"datasetClient":{"id":"test1_97d170e1550eee4afc0af065b78cda302a97674c","datasetId":"test1","collisionCount":0,"queryParams":{},"metaData":{},"lastAccessed":1497430670734,"active":true}}`

**Comment by wtrocki** [comment]
Resolved in PR.
