### ISSUE TITLE
Allow to add authentication/authorisation info

### ISSUE THREAD

**Issue by wtrocki** [feedhenry/fh-sync-js#6]
Sync currently using only one single endpoint to do all data operations.
This makes difficult to apply any security mechanisms which are mostly endpoint based.
Investigate how to add custom security on top of sync.

## Why we need it?

Without security anyone who is authenticated can have access to any resource that is backed by sync managed database. Users can modify filters or even delete entire datasets.

## How

We need to introduce plugin that will use existing sync extensibility mechanism (interceptors)
and allow users to define security for sync based api. Plugin should abstract from actual security implementation.

**Comment by wtrocki** [comment]
See also: https://issues.jboss.org/browse/RAINCATCH-896

**Comment by wei-lee** [comment]
@wtrocki are you talking about client API, or server API here?

For server APIs, given that the sync function can be invoked from any route, I think it should be the application's responsibility to secure the endpoints, just like any other routes.

For the client API, I think we can provide an API to allow users to inject authentication/authorisation to the request, something like this:


```js
sync.onAuth = function(req, callback){
  //inject authentication/authorisation info to the request
 return callback(null, req);
}
```

Also I think this will related to #8. If user can provide their own http request handler, then they can decide how to provide the authentication/authorisation info.

**Comment by wtrocki** [comment]
#8 will resolve problem in the client and I already have this covered.
I was just curious what will be the best pattern to do this on server.

Currently sync has just single endpoint as in example:
https://github.com/feedhenry/fh-sync/blob/master/examples/basic-express-example/server.js#L22-L34

I was thinking about 2 options to resolve it on server:

1) Keeping single endpoint with security middleware
This security middleware will do matching against some static data structure:
```
{
   "role": "User",
   "datasets": [
      {
         "name": "test",
         "actions": [
            "CREATE"
         ]
      }
   ]
}
```

2) Using separate endpoints for datasets
For this we will be able to use standard middleware:
```
app.post('/sync/mydataset/create', keycloakMiddleware("ROLE_USER"), function (req, res) {
...
}
``

I like first option as this can possibly be some plain json file delivered by users that will want to protect some particular datasets (and do not apply any sec on the rest).

**Comment by wei-lee** [comment]
@wtrocki Right, I think I get what you mean. But I am not sure if sync needs to care about how the security checks are implemented, because it is a problem that is not specific to sync, but to the app in general. On the client side, before data is being created/update/delete, user can perform security checks first, like this:

```js
function createData(dataset, cb) {
  if( currentUser.can("create", dataset) ) {
     return sync.create(dataset, data, cb);
  } else {
    return cb(null, new Error("not authorised"));
  }
}
```

On the server side, we can either reuse the request intercepters, or add new hooks into the sync to allow security checks. For example:

```js
sync.onDataCreate = function(dataset, data, request, cb) {
  //user can perform security checks.
  var authorsied = true;
  return cb(null, authorsied);
}
```

Role based or not, I think that's the implementation detail of the app, not for the sync itself.

WDYT?

**Comment by wei-lee** [comment]
@david-martin @jasonmadigan @evanshortiss FYI. any thoughts on this?

**Comment by wtrocki** [comment]
@wei-lee - Agreed with details. I was thinking here about something like sync security plugin, but actually this can be part of the reusable raincatcher-sync module.

**Comment by evanshortiss** [comment]
@wei-lee @wtrocki sync should not really be concerned with this IMO. This is application logic I would think.

Probably needs wider discussion but I think generally something like so: 

```js
const auth = require('lib/auth');
const sync = require('fh-sync')({
  storage: require('fh-sync-mongodb')
});
const parser = require('body-parser').json();

app.use(auth.protect()); // verifies every request contains a cookie/jwt/whatever

// This is available to any authorised users
app.get('/items', sync.listHandler());

// Only admins can modify/create items
// If the cookie/token is not an admin one then return unauthorized http 401
app.put('/items', auth.protect('admin'), parser, sync.updateHandler());
app.post('/items', auth.protect('admin'), parser, sync.createHandler());
```

Sync can be agnostic of authentication in this manner. Thoughts? I think making pieces composable makes life easier for everyone involved meaning the maintainer and the module user.

**Comment by evanshortiss** [comment]
FYI the sample above is similar to how keycloak middleware works and is how I would do auth without keycloak too. I don't want actual route handler to be concerned about auth/roles whenever possible and instead leverage middleware stack layering. Testing becomes easier due to isolation of logic/components, and as already stated you can compose pieces more elegantly.

**Comment by david-martin** [comment]
Sync is concerned with syncing of data between 1 or more clients and the server. Security is not a core function, but security of that data is imperative to the user.
We should have a good example of how to use Sync in a secure way.
That could be via a sample application, or a 'sync plugin' as @wtrocki  mentions, or both.

So it is possible with @evanshortiss middleware example, or using [interceptRequest](https://access.redhat.com/documentation/en-us/red_hat_mobile_application_platform_hosted/3/html/cloud_api/fh-sync#fh-sync-interceptrequest) (apologies for the downstream link) https://github.com/feedhenry/fh-sync/blob/master/lib/sync-server.js#L365

If security was to become a core function of sync, it should still be possible for a developer to use their own security model for the data.

**Comment by wtrocki** [comment]
I'm going to work on security example/plugin that will include role based authentication. While sync should not really care about security we need to make sure that it's possible to secure and add roles to specific data handler actions.

**Comment by evanshortiss** [comment]
@wtrocki @david-martin we've used interceptors in the past, but the main issue with that is you can't control status codes and need to rewire your authentication in a sync-specific manner. Having both options is great of course, and I'm not sure what the future plans are but bring able to bind specific CRUDL handlers in an express-like manner as in my example would be a neat goal.

Meant to CC @MikeyBurkman

**Comment by wtrocki** [comment]
We have it tracked in the jira for Rainatcher project: 
https://issues.jboss.org/browse/RAINCATCH-962
