### ISSUE TITLE
Add default request handler for upstream support

### ISSUE THREAD

**Issue by wtrocki** [feedhenry/fh-sync-js#8]
Add default request handler that will be used for community based sync. Fh-js-sdk will use custom one wrapping  fh.cloud

**Comment by damienomurchu** [comment]
See example for default handler implementation. This implementation should be pulled into app as separate js file.
````
  $fh.sync.setCloudHandler(function (params, success, failure) {
      $.ajax({
        'path': 'http://localhost:8000/mbaas/sync/' + params.dataset_id,
        'method': 'post',
        'data': params.req
      }, function (res) {
        callbackCalled = true;
        success(res);
      }, function (msg, err) {
        callbackCalled = true;
        failure(msg, err);
    });
  });
```

**Comment by wtrocki** [comment]
Basic idea here is that sync will allow to overload handlers and use for example fh-cloud.
Default handler should accept sync cloud url in form of environment variable

**Comment by wtrocki** [comment]
Implementation under review. Closing as finished.
